{CometDelivery: {F0: 2e5, F1: 2e8, tau: 0.15e9}, Convection: {F0: 1e-8, F1: 3e-8,
    tau: 150e6}, Debug: false, Erosion: {alpha: '9.08e-04', uniform_growth: false},
  HydrothermalCirculation: {F0: 1e-7, F1: 3e-7, F_p: 0.5, tau: 150e6}, OutFolder: output,
  Output: 10e6, Precipitation: {VOcean: 1.35e21, flux: 0, max_conc: 2.2e-06}, Processes: [
    Erosion, WindErosion, Subduction, Volcanism, Precipitation, CometDelivery, Convection,
    HydrothermalCirculation], Rainout: {flux: 3.19e8, uniform_growth: false}, Reservoirs: {
    Atmosphere: {InitMasses: {p: 2.8e7}}, CCrust: {InitMasses: {p: 1.4e19}}, LMantle: {
      InitMasses: {p: 6e20}}, OCrust: {InitMasses: {p: 7.2e18}}, Oceans: {InitMasses: {
        p: 9.3e13}}, Sediments: {InitMasses: {p: 4.0e18}}, UMantle: {InitMasses: {
        p: 2.2e20}}}, Species: [p], Subduction: {accretion: 0.3, tau: 100e6}, Timestep: 5e3,
  Tmax: 4500e6, Volcanism: {F_MORB: 20, F_arc: 5, F_hotspot: 2.5, Factor: 3, P_Conc_Ratio_ARC: 5.0,
    P_Conc_Ratio_HS: 4.6, P_Conc_Ratio_MORB: 4.6, density: 2800, tau: 150e6}, WindErosion: {
    beta: 2.7e-05, moved_Oc_vol: 2.5e10, satur: 2.8e7, uniform_growth: false}, atm_ox: 0.2,
  man_ox: 0.2}
